nginx:
  image: nginx:latest
  ports:
    - 8888:80
  volumes:
    - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html
  links:
    - php

php:
  build: .
  volumes:
    - .:/var/www/html
  links:
    - mysql

mysql:
  image: mysql:latest
  volumes:
    - ./mysql:/var/lib/mysql
  ports:
    - 3360:3306
  expose:
    - 3306
  environment:
    - MYSQL_ROOT_PASSWORD=12345678
