mrgenius_index:
  path : /
  defaults:  { _controller: AppBundle:Default:index }

mrgenius_info:
  path : /info
  defaults:  { _controller: AppBundle:Default:info }

mrgenius_update:
  path : /update
  defaults:  { _controller: AppBundle:Default:update }

mrgenius_import:
  path : /import
  defaults:  { _controller: AppBundle:Default:import }