mrgenius_index:
  path : /
  defaults:  { _controller: AppBundle:Default:index }

mrgenius_prediction_goalkeepers:
  path : /goalkeepers
  defaults:  { _controller: AppBundle:Default:predictGoalkeepers }

mrgenius_prediction_attackers:
  path : /attackers
  defaults:  { _controller: AppBundle:Default:predictAttackers }

mrgenius_prediction_defenders:
  path : /defenders
  defaults:  { _controller: AppBundle:Default:predictDefenders }

mrgenius_prediction_midfielders:
  path : /midfielders
  defaults:  { _controller: AppBundle:Default:predictMidfielders }

mrgenius_import_history:
  path : /import/history
  defaults:  { _controller: AppBundle:Data:importHistory }

mrgenius_import_teams:
  path : /import/teams
  defaults:  { _controller: AppBundle:Data:importTeams }

mrgenius_import_players:
  path : /import/players
  defaults:  { _controller: AppBundle:Data:importPlayers }
