mrgenius_index:
  path : /
  defaults:  { _controller: AppBundle:Default:index }

mrgenius_history_import:
  path : /history/import
  defaults:  { _controller: AppBundle:Data:importHistory }

mrgenius_info:
  path : /info
  defaults:  { _controller: AppBundle:Default:info }

mrgenius_update:
  path : /update
  defaults:  { _controller: AppBundle:Default:update }

mrgenius_statistics_positions:
  path : /statistics/positions
  defaults:  { _controller: AppBundle:Statistics:positions }

mrgenius_recommendations:
  path : /recommendations
  defaults:  { _controller: AppBundle:Default:recommendations }