services:
  mrgenius.importservice:
    class: AppBundle\Service\ImportService
    public: true
    autowire: true

  mrgenius.optionsservice:
    class: AppBundle\Service\OptionsService
    public: true
    autowire: true

  mrgenius.statisticsservice:
    class: AppBundle\Service\StatisticsService
    public: true
    autowire: true

  mrgenius.dataservice:
    class: AppBundle\Service\DataService
    public: true
    autowire: true
