services:
  mrgenius.importservice:
    class: AppBundle\Service\ImportService
    public: true
    autowire: true

  mrgenius.optionsservice:
    class: AppBundle\Service\OptionsService
    public: true
    autowire: true
